/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export const Model = ({scroll, small}) => {
    const group = useRef()
    const { nodes, materials } = useGLTF('./penguin.gltf')
    
    // Animate model
    useFrame((state) => {
        group.current.rotation.x = 0.04 * (scroll / 20)
        group.current.rotation.y = 0.02 * (scroll / 20)
    })

    return (
        <group ref={group} dispose={null} scale={small}>
        <group scale={[0.78, 1.13, 0.33]} rotation={[0.21, 0, 0]} >
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere021.geometry}
            material={materials['Clay.004']}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere021_1.geometry}
            material={materials.Yello}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere021_2.geometry}
            material={materials.Clay}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere021_3.geometry}
            material={materials['Clay.003']}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere021_4.geometry}
            material={materials['Clay.006']}
            />
        </group>
        </group>
    )
}

useGLTF.preload('/penguin.gltf')
